#!/usr/bin/env bash

export GMAIL_USER="PASTE_HERE_GMAIL_ADDRESS"
export GMAIL_PASSWORD="PASTE_HERE_GMAIL_PASSWORD"
export B2_KEY_ID="PASTE_HERE_B2_KEY_ID"
export B2_APP_KEY="PASTE_HERE_B2_APP_KEY"
export B2_BUCKET="PASTE_HERE_B2_BUCKET_NAME"
